#pragma once

#include <string>
#include <vector>

#include "mcp/handler/prompt_router.hpp"
#include "mcp/model/prompt.hpp"

/// @file
/// C++ preprocessor macros for prompt registration, mirroring
/// Rust's #[prompt], #[prompt_router], and #[prompt_handler] macros.

// =============================================================================
// MCP_PROMPT: Declare a prompt's metadata
// =============================================================================

/// Declare a prompt method's metadata. Use inside a class body.
///
/// Usage:
///   MCP_PROMPT(MyServer, my_prompt, "my_prompt", "Description",
///              {{"arg1", "Argument 1 desc", true}})
///
/// The args parameter should be a vector<PromptArgDef>.
#define MCP_PROMPT(cls, method, name, desc, ...) \
    static mcp::Prompt __mcp_prompt_meta_##method() { \
        mcp::Prompt prompt; \
        prompt.name = name; \
        prompt.description = desc; \
        auto args_init = std::vector<mcp::PromptArgument>(__VA_ARGS__); \
        if (!args_init.empty()) { \
            prompt.arguments = std::move(args_init); \
        } \
        return prompt; \
    }

// =============================================================================
// MCP_PROMPT_ROUTE: Register a prompt in the router
// =============================================================================

/// Register a prompt method as a route in a PromptRouter.
///
/// Usage (in constructor or init method):
///   MCP_PROMPT_ROUTE(MyServer, my_prompt)
///
/// The class must have:
/// - A static __mcp_prompt_meta_my_prompt() (generated by MCP_PROMPT)
/// - A method: awaitable<GetPromptResult> my_prompt(PromptCallContext ctx)
/// - A member: PromptRouter prompt_router_
#define MCP_PROMPT_ROUTE(cls, method) \
    prompt_router_.add_route( \
        cls::__mcp_prompt_meta_##method(), \
        [this](mcp::PromptCallContext ctx) -> boost::asio::awaitable<mcp::GetPromptResult> { \
            co_return co_await this->method(std::move(ctx)); \
        })

// =============================================================================
// MCP_PROMPT_HANDLER: Generate handler overrides
// =============================================================================

/// Generate list_prompts and get_prompt overrides that delegate to the router.
///
/// Usage (in the class body):
///   MCP_PROMPT_HANDLER(MyServer)
///
/// The class must have a PromptRouter prompt_router_ member.
#define MCP_PROMPT_HANDLER(cls) \
    boost::asio::awaitable<mcp::ListPromptsResult> list_prompts( \
        std::optional<mcp::PaginatedRequestParams>, \
        mcp::ServerRequestContext) override { \
        mcp::ListPromptsResult result; \
        result.prompts = prompt_router_.list_prompts(); \
        co_return result; \
    } \
    boost::asio::awaitable<mcp::GetPromptResult> get_prompt( \
        mcp::GetPromptRequestParams params, \
        mcp::ServerRequestContext ctx) override { \
        mcp::PromptCallContext prompt_ctx{ \
            std::move(params.name), \
            std::move(params.arguments), \
            std::move(ctx) \
        }; \
        co_return co_await prompt_router_.get_prompt_result(std::move(prompt_ctx)); \
    }
