#pragma once

#include <string>

#include "mcp/handler/tool_router.hpp"
#include "mcp/model/tool.hpp"

/// @file
/// C++ preprocessor macros that serve as the equivalent of Rust's
/// #[tool], #[tool_router], and #[tool_handler] procedural macros.

namespace mcp {

/// Helper to generate a JSON Schema object for a given type T.
/// T must have a static json_schema() method or be void for empty schema.
template <typename T>
json generate_schema() {
    if constexpr (std::is_void_v<T>) {
        return json{{"type", "object"}, {"properties", json::object()}};
    } else {
        // Default: call T::json_schema() if it exists
        if constexpr (requires { T::json_schema(); }) {
            return T::json_schema();
        } else {
            return json{{"type", "object"}, {"properties", json::object()}};
        }
    }
}

} // namespace mcp

// =============================================================================
// MCP_TOOL: Declare a tool's metadata
// =============================================================================

/// Declare a tool method's metadata. Use inside a class body.
///
/// Usage:
///   MCP_TOOL(MyServer, my_tool, "my_tool", "Description of my tool", MyParams)
///
/// This generates a static method __mcp_tool_meta_my_tool() that returns a Tool.
#define MCP_TOOL(cls, method, name, desc, schema_type) \
    static mcp::Tool __mcp_tool_meta_##method() { \
        auto schema = mcp::generate_schema<schema_type>(); \
        auto schema_ptr = std::make_shared<mcp::JsonObject>( \
            schema.is_object() \
                ? schema.get<mcp::JsonObject>() \
                : mcp::JsonObject{}); \
        mcp::Tool tool; \
        tool.name = name; \
        tool.description = desc; \
        tool.input_schema = schema_ptr; \
        return tool; \
    }

// =============================================================================
// MCP_TOOL_ROUTE: Register a tool in the router
// =============================================================================

/// Register a tool method as a route in a ToolRouter.
///
/// Usage (in constructor or init method):
///   MCP_TOOL_ROUTE(MyServer, my_tool)
///
/// The class must have:
/// - A static __mcp_tool_meta_my_tool() (generated by MCP_TOOL)
/// - A method: awaitable<CallToolResult> my_tool(ToolCallContext ctx)
/// - A member: ToolRouter router_
#define MCP_TOOL_ROUTE(cls, method) \
    router_.add_route( \
        cls::__mcp_tool_meta_##method(), \
        [this](mcp::ToolCallContext ctx) -> boost::asio::awaitable<mcp::CallToolResult> { \
            co_return co_await this->method(std::move(ctx)); \
        })

// =============================================================================
// MCP_TOOL_HANDLER: Generate handler overrides
// =============================================================================

/// Generate call_tool and list_tools overrides that delegate to the router.
///
/// Usage (in the class body):
///   MCP_TOOL_HANDLER(MyServer)
///
/// The class must have a ToolRouter router_ member.
#define MCP_TOOL_HANDLER(cls) \
    mcp::ServerCapabilities capabilities() override { \
        auto caps = mcp::ServerCapabilities{}; \
        if (!router_.empty()) { \
            caps.tools = mcp::ToolsCapability{}; \
        } \
        return caps; \
    } \
    boost::asio::awaitable<mcp::ListToolsResult> list_tools( \
        std::optional<mcp::PaginatedRequestParams>, \
        mcp::ServerRequestContext) override { \
        mcp::ListToolsResult result; \
        result.tools = router_.list_tools(); \
        co_return result; \
    } \
    boost::asio::awaitable<mcp::CallToolResult> call_tool( \
        mcp::CallToolRequestParams params, \
        mcp::ServerRequestContext ctx) override { \
        mcp::ToolCallContext tool_ctx{ \
            std::string(params.name), \
            std::move(params.arguments), \
            std::move(ctx) \
        }; \
        co_return co_await router_.call_tool(std::move(tool_ctx)); \
    }

// =============================================================================
// MCP_TOOL_ROUTER: Declare a complete tool router in one macro
// =============================================================================

/// Convenience: Declare a ToolRouter and register multiple tools.
///
/// Usage:
///   MCP_TOOL_ROUTER(MyServer, tool1, tool2, tool3)
///
/// This generates an init_tools() method. Call it in your constructor.
#define MCP_TOOL_ROUTER_INIT(cls, ...) \
    void init_tools() { \
        MCP_TOOL_ROUTER_EXPAND(cls, __VA_ARGS__) \
    }

// Helper to expand variadic tool registrations
#define MCP_TOOL_ROUTER_EXPAND(cls, ...) \
    MCP_TOOL_ROUTER_FOR_EACH(cls, __VA_ARGS__)

// For-each over variadic args (up to 15 tools)
#define MCP_TOOL_ROUTER_FOR_EACH(cls, ...) \
    MCP_TOOL_ROUTER_FOR_EACH_IMPL(cls, __VA_ARGS__, _END)

#define MCP_TOOL_ROUTER_FOR_EACH_IMPL(cls, m, ...) \
    MCP_TOOL_ROUTE(cls, m); \
    MCP_TOOL_ROUTER_FOR_EACH_NEXT(cls, __VA_ARGS__)

#define MCP_TOOL_ROUTER_FOR_EACH_NEXT(cls, m, ...) \
    MCP_TOOL_ROUTER_FOR_EACH_CHECK(cls, m, __VA_ARGS__)

#define MCP_TOOL_ROUTER_FOR_EACH_CHECK(cls, m, ...) \
    MCP_TOOL_ROUTER_FOR_EACH_##m(cls, __VA_ARGS__)

#define MCP_TOOL_ROUTER_FOR_EACH__END(cls, ...)

// If not _END, register and continue
#ifndef MCP_TOOL_ROUTER_FOR_EACH__END
#define MCP_TOOL_ROUTER_FOR_EACH__END(cls, ...)
#endif
